package java15;

public class ExceptionTest2 {

	public void call() {
		int[] num = { 1, 2, 3 };
		num[3] = 4; // 에러

		System.out.println("출력 가능?");

	}
}
